spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/egp
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.modern.egp: DEBUG